- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Zabbix Agent
  apt:
    name: ["zabbix-agent"]
    state: present

- name: Copy Zabbix Agent configuration file
  copy:
    src: ./zabbix_agent/templates/zabbix_agent.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: "0644"
